server:
  port: 8888
spring:
  application:
    name: cloud-gateway-eureka
  #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
  cloud:
    gateway:
     discovery:
        locator:
         enabled: true
     routes:
     - id: add_request_parameter_route
       uri: lb://eurekaclient-producer
       filters:
       - AddRequestParameter=foo, bar
       #会给匹配的每个请求添加上foo=bar的参数和值
       predicates:
       - Method=GET
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
#调整相 gateway 包的 log 级别，以便排查问题
logging:
  level:
    org.springframework.cloud.gateway: debug