spring:
  application:
    name: zipkin-customer
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://192.168.56.103:9411/ # 指定了 Zipkin 服务器的地址
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
