server:
  port: 9002
spring:
  application:
    name: user-service
  #数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/oauth?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
#开启熔断器
feign:
  hystrix:
    enabled: true
