server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
      - id: hystrix_route
        uri: lb://spring-cloud-producer
        predicates:
        - Path=/consumingserviceendpoint
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/incaseoffailureusethis
            #fallbackUri: forward:/incaseoffailureusethis配置了 fallback 时要会调的路径，当调用 Hystrix 的 fallback 被调用时，请求将转发到/incaseoffailureuset这个 URI。
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
#调整相 gateway 包的 log 级别，以便排查问题
logging:
  level:
    org.springframework.cloud.gateway: debug